version: "3.0"
services: 
  ojala:
    build: ./OJALA #'ruta del dockerfile'
    ports: 
      - 8083:80
    volumes:
      - "./OJALA:/var/www/html" #'ruta del dockerfile'
    container_name: ojala
    depends_on:
      - datos
  correo:
    build: ./CORREO #'ruta del dockerfile'
    volumes:
      - "./correo:/var/www/html" #'ruta del dockerfile'
    container_name: correo
    depends_on: 
      - datos
  datos:
    build: ./DATOS
  cestero:
    build: ./CESTERO
    volumes:
      - "./CESTERO:/var/www/html"
    container_name: cestero
    depends_on:
      - datos
